// Generates dist/sw.js after `vite build`.
//
// Hand-rolled rather than using vite-plugin-pwa: that plugin pulls in the
// workbox-build toolchain, which currently drags in eight high-severity
// transitive advisories for what amounts to forty lines of cache logic.
//
// The precache list has to be generated because Vite hashes asset filenames,
// so it can't be written by hand.

import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = resolve(ROOT, 'dist')
const BASE = process.env.BASE_PATH || '/'

/** Everything except the service worker itself and source maps. */
function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) walk(full, out)
    else out.push(full)
  }
  return out
}

// The dictionaries are ~1 MB gzipped and most sessions never open a tooltip,
// so they are deliberately NOT precached — the first lookup fetches them and
// the runtime cache keeps them offline from then on.
const files = walk(DIST)
  .map((f) => relative(DIST, f))
  .filter((f) => f !== 'sw.js' && !f.endsWith('.map') && !f.startsWith('dict/'))
  .sort()

const urls = files.map((f) => BASE + f.split('\\').join('/'))

// Cache name is content-derived, so a deploy that changes nothing does not
// invalidate the user's cache, and one that changes anything does.
const version = createHash('sha256')
  .update(files.map((f) => readFileSync(join(DIST, f))).join('\u0000'))
  .digest('hex')
  .slice(0, 12)

const sw = `// Generated by scripts/build-sw.ts — do not edit.
const CACHE = 'japanese-srs-${version}'
const BASE = ${JSON.stringify(BASE)}
const INDEX = BASE + 'index.html'
const PRECACHE = ${JSON.stringify(urls, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// ignoreVary is essential, not an optimisation. Cache entries created by
// addAll() carry the server's Vary header, and a module-script request sends
// different headers than the one that populated the cache — so a plain
// caches.match() MISSES the very files it just precached, silently falls
// through to the network, and the app renders blank offline.
const MATCH = { ignoreVary: true }

async function fromCacheThenNetwork(request) {
  const cached = await caches.match(request, MATCH)
  if (cached) return cached

  const response = await fetch(request)
  if (response.ok && response.type === 'basic') {
    const copy = response.clone()
    const cache = await caches.open(CACHE)
    cache.put(request, copy)
  }
  return response
}

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return
  if (new URL(request.url).origin !== self.location.origin) return

  // Every route is the same SPA shell, so navigations resolve to index.html.
  // Cache-first is what makes the app open with no connection.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match(INDEX, MATCH)
        .then((cached) => cached || fetch(request))
        .catch(() => caches.match(INDEX, MATCH)),
    )
    return
  }

  event.respondWith(
    fromCacheThenNetwork(request).catch(() => caches.match(request, MATCH)),
  )
})
`

writeFileSync(join(DIST, 'sw.js'), sw)
console.log(`✓ dist/sw.js — ${urls.length} files precached (cache japanese-srs-${version})`)
