import { mount } from 'svelte'
import './app.css'
import App from './App.svelte'
import { store } from './lib/store.svelte.ts'
import { applyTheme } from './lib/theme.ts'

// The inline script in index.html has already set the attribute, so this is
// not what prevents the flash — it paints the browser chrome to match and
// starts watching for the OS flipping under a 'system' setting.
applyTheme(store.settings.theme)

const app = mount(App, { target: document.getElementById('app')! })

// Only in production builds: dist/sw.js is generated by scripts/build-sw.ts,
// and registering a stale worker in dev would serve cached modules over HMR.
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register(`${import.meta.env.BASE_URL}sw.js`, { scope: import.meta.env.BASE_URL })
      .catch((err) => console.warn('[sw] registration failed', err))
  })
}

export default app
